### ISSUE TITLE
Problem with unknown words

### ISSUE THREAD

**Issue by tranquoclongt1** [suicao/Vn-Accent-Restorer#1]
Hi Khoi,
Thanks for your excellent works. I tested the both models (RNN and TransformerDecoder) But the modified model seems like cannot work with sentences having unknown word (ex: technical words)?

**Comment by suicao** [comment]
Can you give me an example i.e the input/output of the model? Was there an error?

If there wasn't an error then I think it's intended behavior, the model will output the original word if it was out of vocabulary. You may need to find another method to handle this.

**Comment by suicao** [comment]
Anyway i fixed a bug where it may cause the model to crash, you can update the code now. Let me know if you have any further issues.

**Comment by tranquoclongt1** [comment]
> Anyway i fixed a bug where it may cause the model to crash, you can update the code now. Let me know if you have any further issues.

Ahh, it worked! I found the problem after digging in the source code, the bug came from that line and you fixed it. Thank you :+1:
